2023 Most Promising Places to Work landing page
parameter1/cox-matthews-associates-websites pull request #212
Opened 2023-03-09 15:49 UTC by flaviogalizia

2023-03-09 15:58 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR #212](https://trello.com/c/DAgG7cDd/279-pr-212)

2023-03-13 17:05 UTC, Shinsina requested changes

2023-03-13 17:05 UTC, Shinsina commented on sites/diverseeducation.com/server/templates/static-pages/mppwsa-yearly.marko
> +$ const nationalPerspective = currentYearData ? currentYearData.ideas: title;
This appears to be looking for the wrong property here and should likely be changed to `const nationalPerspective = currentYearData ? currentYearData.nationalPerspective : title;`

2023-03-13 17:05 UTC, Shinsina commented on sites/diverseeducation.com/server/templates/static-pages/mppwsa-yearly.marko
> +         </if>
Check the tabbing of the tags here this doesn't appear to be correct (as in the tags aren't aligned inner to outer)

2023-03-16 20:14 UTC, merged